"""Database-backed downloadable inventory reports."""

from datetime import datetime

from fastapi import APIRouter, Depends
from fastapi.responses import Response
from fpdf import FPDF
from sqlalchemy import func
from sqlalchemy.orm import Session

from backend import models
from backend.database import get_db

router = APIRouter(prefix="/reports", tags=["Reports"])
LOW_STOCK_THRESHOLD = 10
INDIGO = (109, 94, 240)


class InventoryReport(FPDF):
    def header(self):
        self.set_text_color(*INDIGO)
        self.set_font("Helvetica", "B", 18)
        self.cell(0, 10, _pdf_text("StockSense - Inventory Report"), new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(100, 103, 112)
        self.set_font("Helvetica", size=9)
        self.cell(0, 6, f"Generated {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(210, 210, 220)
        self.line(self.l_margin, self.get_y() + 2, self.w - self.r_margin, self.get_y() + 2)
        self.ln(8)

    def footer(self):
        self.set_y(-14)
        self.set_draw_color(220, 220, 226)
        self.line(self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y())
        self.set_y(-11)
        self.set_text_color(100, 103, 112)
        self.set_font("Helvetica", size=8)
        self.cell(0, 6, f"Generated by StockSense                                      Page {self.page_no()}", align="C")

    def section(self, title: str):
        self.set_text_color(*INDIGO)
        self.set_font("Helvetica", "B", 12)
        self.cell(0, 8, _pdf_text(title), new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(*INDIGO)
        self.set_line_width(0.35)
        self.line(self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y())
        self.ln(3)


def _pdf_text(value) -> str:
    """Keep built-in Helvetica text within its supported Latin-1 range."""
    return str(value or "").replace("—", "-").replace("–", "-").encode("latin-1", "replace").decode("latin-1")


def _table_header(pdf: InventoryReport, headings: list[str], widths: list[float]):
    pdf.set_fill_color(232, 230, 249)
    pdf.set_text_color(32, 32, 46)
    pdf.set_font("Helvetica", "B", 8.5)
    for heading, width in zip(headings, widths):
        pdf.cell(width, 8, _pdf_text(heading), border=0, fill=True)
    pdf.ln()


def _table_row(pdf: InventoryReport, values: list[str], widths: list[float], row_index: int, status: str | None = None):
    if row_index % 2:
        pdf.set_fill_color(246, 247, 249)
    else:
        pdf.set_fill_color(255, 255, 255)
    pdf.set_font("Helvetica", size=8)
    for index, (value, width) in enumerate(zip(values, widths)):
        if status and index == len(values) - 1:
            pdf.set_font("Helvetica", "B", 8)
            pdf.set_text_color(*( (20, 125, 65) if status == "In Stock" else (181, 112, 12) if status == "Low Stock" else (190, 45, 50) ))
        else:
            pdf.set_font("Helvetica", size=8)
            pdf.set_text_color(35, 37, 45)
        pdf.cell(width, 7, _pdf_text(value)[: max(8, int(width / 1.7))], fill=True)
    pdf.ln()


@router.get("/inventory-pdf", summary="Download an inventory PDF report")
def inventory_pdf(db: Session = Depends(get_db)):
    """Calculate report totals directly from Product, Location, and StockMove rows."""
    products = db.query(models.Product).order_by(models.Product.name, models.Product.id).all()
    totals_query = (
        db.query(models.StockMove.product_id, func.coalesce(func.sum(models.StockMove.quantity_change), 0))
        .group_by(models.StockMove.product_id)
        .all()
    )
    totals = {product_id: int(stock) for product_id, stock in totals_query}
    by_location = (
        db.query(
            models.Location.name,
            models.Product.name,
            models.Product.sku,
            func.sum(models.StockMove.quantity_change).label("quantity"),
        )
        .join(models.StockMove, models.StockMove.location_id == models.Location.id)
        .join(models.Product, models.Product.id == models.StockMove.product_id)
        .group_by(models.Location.id, models.Location.name, models.Product.id, models.Product.name, models.Product.sku)
        .having(func.sum(models.StockMove.quantity_change) > 0)
        .order_by(models.Location.name, models.Product.name)
        .all()
    )

    stocks = [totals.get(product.id, 0) for product in products]
    pdf = InventoryReport(orientation="P", unit="mm", format="A4")
    pdf.set_margins(12, 12, 12)
    pdf.set_auto_page_break(auto=False)
    pdf.add_page()

    pdf.section("Summary")
    summary = [
        ("Total products", len(products)),
        ("Total units", sum(max(stock, 0) for stock in stocks)),
        ("Low-stock items (<10)", sum(stock < LOW_STOCK_THRESHOLD for stock in stocks)),
        ("Out-of-stock items", sum(stock <= 0 for stock in stocks)),
    ]
    box_width = (pdf.epw - 9) / 4
    for label, value in summary:
        x, y = pdf.get_x(), pdf.get_y()
        pdf.set_fill_color(246, 247, 250)
        pdf.rect(x, y, box_width, 17, style="F")
        pdf.set_xy(x + 2, y + 2)
        pdf.set_text_color(100, 103, 112)
        pdf.set_font("Helvetica", size=7)
        pdf.cell(box_width - 4, 4, _pdf_text(label))
        pdf.set_xy(x + 2, y + 7)
        pdf.set_text_color(32, 32, 46)
        pdf.set_font("Helvetica", "B", 13)
        pdf.cell(box_width - 4, 7, str(value))
        pdf.set_xy(x + box_width + 3, y)
    pdf.set_xy(pdf.l_margin, pdf.get_y() + 23)

    pdf.section("Stock by Location")
    location_widths = [35, 75, 35, 41]
    if not by_location:
        pdf.set_text_color(100, 103, 112)
        pdf.set_font("Helvetica", size=9)
        pdf.cell(0, 7, "No positive stock is currently recorded at any location.", new_x="LMARGIN", new_y="NEXT")
    else:
        groups: dict[str, list] = {}
        for row in by_location:
            groups.setdefault(row[0], []).append(row)
        for location, rows in groups.items():
            if pdf.get_y() > 260:
                pdf.add_page()
                pdf.section("Stock by Location (continued)")
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(35, 37, 45)
            pdf.cell(0, 7, _pdf_text(location), new_x="LMARGIN", new_y="NEXT")
            _table_header(pdf, ["Location", "Product", "SKU", "Quantity"], location_widths)
            for index, row in enumerate(rows):
                if pdf.get_y() > 270:
                    pdf.add_page()
                    pdf.section("Stock by Location (continued)")
                    pdf.set_font("Helvetica", "B", 9)
                    pdf.set_text_color(35, 37, 45)
                    pdf.cell(0, 7, _pdf_text(location), new_x="LMARGIN", new_y="NEXT")
                    _table_header(pdf, ["Location", "Product", "SKU", "Quantity"], location_widths)
                _table_row(pdf, ["", row[1], row[2], str(int(row[3]))], location_widths, index)
            pdf.ln(2)

    pdf.section("Product-wise Breakdown")
    product_widths = [50, 32, 44, 32, 28]
    _table_header(pdf, ["Product Name", "SKU", "Category", "Total Stock", "Status"], product_widths)
    for index, (product, stock) in enumerate(zip(products, stocks)):
        if stock <= 0:
            status_text = "Out of Stock"
        elif stock < LOW_STOCK_THRESHOLD:
            status_text = "Low Stock"
        else:
            status_text = "In Stock"
        if pdf.get_y() > 270:
            pdf.add_page()
            pdf.section("Product-wise Breakdown (continued)")
            _table_header(pdf, ["Product Name", "SKU", "Category", "Total Stock", "Status"], product_widths)
        _table_row(pdf, [product.name, product.sku, product.category, str(stock), status_text], product_widths, index, status_text)

    content = bytes(pdf.output())
    filename = f"stocksense-inventory-report-{datetime.now().date().isoformat()}.pdf"
    return Response(
        content=content,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
